version: '3.8'

services:
    frontend:
        image: frontend
        build: ./frontend
        restart: always
        networks:
            - mathsoc-network
        ports:
            - "3000:3000"
    backend:
        image: backend
        build: ./backend
        restart: always
        networks:
            - mathsoc-network
        ports:
            - "8080:8080"
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        restart: always
        expose:
            - "27017"
        ports:
            - "27017:27017"

networks:
    mathsoc-network:
        driver: bridge